# Generated by Django 5.1.1 on 2024-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.DateField(),
        ),
    ]
